# Site settings
name: Kilian Ashley
title: Kilian Ashley | Portfolio
description: Biogeochemist focused on climate related issues
url: https://kilian-ashley.github.io/
baseurl: ''
email: kashley@usc.edu
cover: https://kilian-ashley.github.io/img/og.png
logo: https://kilian-ashley.github.io/img/emojis/fire.png
resume: https://kilian-ashley.github.io/resume.pdf
social:
  - title: email
    url: mailto:kashley@usc.edu
  # - title: instagram
  #   url: https://instagram.com/seismacita
  # - title: github
    # url: https://github.com/kilian-ashley
  # - title: twitter
  #   url: https://twitter.com/seismacita
  - title: linkedin
    url: https://www.linkedin.com/in/kilian-ashley-ab246771/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
